### ISSUE TITLE
indent는 4칸이 기본이죠...

### ISSUE THREAD

**Issue by dongjinkang** [MediaEden/EdenCore#1]
https://github.com/MediaEden/EdenCore/blob/f51e7e3438cb11a2695302b9c8ca2fa122bb63cc/src/Greeter.cpp#L8-L18

**Comment by revol300** [comment]
코딩 스타일 뭐 따라가는지 README에 써줘요

**Comment by cmj225** [comment]
@dongjinkang  indent는 2칸이 국룰 아니냐
@revol300 clang_format 참조

**Comment by dongjinkang** [comment]
대장님이 꼭 2칸으로 해야겠다고 하시니 어쩔수없죠...
